[package]
name = "libmdbx"
version = "0.7.0"
edition = "2024"
license = "Apache-2.0"
description = "Idiomatic and safe MDBX wrapper."
documentation = "https://docs.rs/libmdbx"
homepage = "https://github.com/vorot93/libmdbx-rs"
repository = "https://github.com/vorot93/libmdbx-rs"
readme = "README.md"
keywords = ["MDBX", "database", "storage-engine", "bindings"]
categories = ["database"]

[lib]
name = "libmdbx"

[workspace]
members = ["mdbx-sys"]

[dependencies]
arrayref = { version = "0.3", optional = true }
arrayvec = { version = "0.7", optional = true }
bytes = { version = "1", optional = true }
bitflags = "2"
ciborium = { version = "0.2", optional = true }
derive_more = { version = "2", features = [
    "deref",
    "deref_mut",
    "display",
    "from",
] }
impls = { version = "1", optional = true }
indexmap = "2"
libc = "0.2"
parking_lot = "0.12"
sealed = "0.7"
tempfile = { version = "3", optional = true }
thiserror = "2"

ffi = { package = "mdbx-sys", version = "=14.3.1", path = "./mdbx-sys" }

lifetimed-bytes = { version = "0.1", optional = true }

[dev-dependencies]
criterion = "0.8"
rand = "0.10"
rand_xorshift = "0.5"
serde = { version = "1", features = ["derive"] }
tempfile = "3"

[features]
bytes = ["dep:bytes"]
cbor = ["orm", "dep:ciborium"]
lifetimed-bytes = ["dep:lifetimed-bytes"]
orm = ["dep:arrayref", "dep:arrayvec", "dep:impls", "dep:tempfile"]

[[bench]]
name = "cursor"
harness = false

[[bench]]
name = "transaction"
harness = false

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
